DROP DATABASE IF EXISTS shop_api CASCADE;
CREATE DATABASE IF NOT EXISTS shop_api;
SET DATABASE = shop_api;

CREATE TABLE IF NOT EXISTS users (
    id SERIAL NOT NULL PRIMARY KEY UNIQUE,
    username STRING NOT NULL UNIQUE,
    email STRING NOT NULL UNIQUE,
    hashed_password NOT NULL STRING,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

